name = "busybeaver"
version = "0.1.0"
defaultTargets = ["beaver"]

# TODO: Do we need this?
# [leanOptions]
# "pp.unicode.fun" = true

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.27.0"

[[require]]
name = "Cli"
git = "https://github.com/leanprover/lean4-cli"
rev = "v4.27.0"

[[lean_lib]]
name = "Busybeaver"

[[lean_exe]]
name = "beaver"
root = "Main"

# TODO: Bring back this to life
# [[lean_exe]]
# name = "gfunc"
# root = "bin.GFunction"
